iziz/libPhoneNumber-iOS

- libPhoneNumber/NBPhoneNumberUtil.h
- libPhoneNumber/NBPhoneNumberUtil.m
Singletons are believed by many people to be a bad pattern. Currently there is no way to instantiate an instance of `NBPhoneNumberUtil` without using the singleton `sharedInstance` class method because the `init` method is not declared in the header file.
I cannot see any reason not to have this method public - it does not prevent anyone from using the shared instances and allows those of us who do not wish to do so to use the init method.
> Declared init method in header file to allow instantiation without using the singleton.

- libPhoneNumber-iOS/libPhoneNumber.h
- libPhoneNumber.xcodeproj/project.pbxproj
Having headers included in the framework but not imported in libPhoneNumber.h causes umbrella header module map warnings.
> Fixing potential build error and module map warnings in Swift projects

- libPhoneNumber.xcodeproj/project.pbxproj
- libPhoneNumber/AppDelegate.m
- libPhoneNumber/NBPhoneNumberDefines.h
- libPhoneNumber/NBPhoneNumberDefines.m
- libPhoneNumber/NBPhoneNumberUtil.m
- libPhoneNumberTests/NBAsYouTypeFormatterTest1.m
- libPhoneNumberTests/NBPhoneNumberUtilTest1.m
- libPhoneNumberTests/NBPhoneNumberUtilTest2.m
The shared string constants in `NBPhoneNumberDefines.h` were defined as static variables.
As a result, they were not actually shared but instead a new instance was created for
every file that imported the header. This commit changes the constants to use external
linkage which makes them truly shared. On top, the pointers were made immutable. Finally,
the special `@"ZZ"` code for unknown regions was added to the public shared string constants.
Since this code can be returned by a number of public library functions, clients should
have a way to check for it other than using the internal string literal `@"ZZ"`.
> Use external linkage & const pointers for shared string constants and make unknown region code public

- libPhoneNumber-iOS/Info.plist
- libPhoneNumber.xcodeproj/project.pbxproj
- libPhoneNumber.xcodeproj/xcshareddata/xcschemes/libPhoneNumber-iOS.xcscheme
- libPhoneNumber.xcodeproj/xcshareddata/xcschemes/libPhoneNumber.xcscheme
- libPhoneNumber/libPhoneNumber-Info.plist
- libPhoneNumberTests/libPhoneNumberTests-Info.plist
This commit updates the project to the recommended settings on the latest official
Xcode release 7.1 (7B91b). This gets rid of a warning displayed when importing the
project through Carthage, for instance.
> Update Xcode project to recommended settings

- libPhoneNumber/NBPhoneNumber.m
- libPhoneNumber/NBPhoneNumberDefines.h
- libPhoneNumber/NBPhoneNumberUtil.m
- libPhoneNumberTests/NBPhoneNumberUtilTest2.m
Objective-C enums that are defined with the NS_ENUM macro are automatically imported
into Swift as Swift enumerations. This allows for easier usage of the enums in Swift.
In addition to wrapping all enum declarations into NS_ENUM, this commit also makes
sure that the correct factory method is used when converting between enum constants
and NSNumbers.
> Use NS_ENUM for better Swift interoperability

- libPhoneNumber.xcodeproj/project.pbxproj
Sorry, this is one more tiny commit to get rid of warnings in Xcode. :)
This commit removes the run script build phase from the test target which called
the RunUnitTests command. The latter is obsolete now since unit test execution
is configured in schemes. Removing the build phase removes a deprecation warning
that appeared when running the tests in Xcode.
In addition, this commit drops invalid and superfluous search paths from the
project file. An invalid framework search path caused a warning when running
the tests in Xcode.
> Remove deprecated call to RunUnitTests and invalid/superfluous search paths

- README.md
There was an error with the example for Swift 2.0
> [BUG FIX] Swift Example Error

- libPhoneNumber/NBAsYouTypeFormatter.m
xcode 7.3 beta2 analyze gives 2 warnings on possible nil values here. This will return a definitive value for those cases and solve the analyze warning
> prevents xc7.3 warnings

- libPhoneNumber/NBPhoneNumberDefines.m
- libPhoneNumber/NBPhoneNumberUtil.m
A project I am working on requires that numbers be obfuscated with the asterisk `*` but the formatting did not work anymore. This change will recognize the asterisk as a character in string so that it will still format accordingly. 
Example: (123) 456-7890 -> (***) **6-7890
> Enable Formatting of Obfuscated Numbers

- libPhoneNumber-iOS.podspec
- libPhoneNumber-tvOS/Info.plist
- libPhoneNumber-tvOS/libPhoneNumber-tvOS.h
- libPhoneNumber-watchOS/Info.plist
- libPhoneNumber-watchOS/libPhoneNumber-watchOS.h
- libPhoneNumber.xcodeproj/project.pbxproj
- libPhoneNumber/NBPhoneNumberUtil.h
- libPhoneNumber/NBPhoneNumberUtil.m
This PR mostly gets tvOS support into libPhoneNumber. To do so, I had to change imports from `#if TARGET_OS_IPHONE && !TARGET_OS_WATCH` to `#if TARGET_OS_IOS`, as `TARGET_OS_IPHONE` is `1` on tvOS. You could keep backwards compatibility with older versions of Xcode by changing it to `#if TARGET_OS_IPHONE && !TARGET_OS_WATCH && !TARGET_OS_TV` but that seemed a bit unwieldy to me.
I also added Xcode targets to build watchOS and tvOS frameworks locally.
> Add tvOS support, watchOS and tvOS Xcode targets

- libPhoneNumber/NBPhoneNumberUtil.h
- libPhoneNumber/NBPhoneNumberUtil.m
- libPhoneNumberTests/NBPhoneNumberUtilTest1.m
Parallel of https://github.com/googlei18n/libphonenumber/pull/1526. 
Also added '#' to DIALLABLE_CHAR_MAPPINGS, since it's in there for Java/JS libPhoneNumber.
The objc port seems to use a mix of 
`NBPhoneNumberUtil-normalizeHelper:normalizationReplacements:removeNonMatches:`
and 
`NSString-stringByReplacingOccurrencesString:withMap:removeNonMatches:`
so I wasn't sure if I should extend the call to other methods that use DIALLABLE_CHAR_MAPPINGS.
> Port normalizeDiallableCharsOnly to Objective C

- libPhoneNumber/NBMetadataHelper.m
`NSString *country = [[NSLocale currentLocale] displayNameForKey:NSLocaleIdentifier value:identifier];` 
The function above will catch empty country name in iOS 8.0.
Therefore, to support iOS 8 in country listing, I've added `[[NSLocale systemLocale] displayNameForKey:NSLocaleIdentifier value:identifier]` to retrieve default English country name if failed to get country name from `[NSLocale currentLocale]`.
Thank you for great library!
> add solution to get country name in iOS8

- libPhoneNumber/NBPhoneNumber.m
- libPhoneNumber/NBPhoneNumberUtil.m
* Using `NSNumber*` as boolean might be confusing. Making the test to `nil` explicit is clearer.
* Protect against `regionCode == nil` by reversing the order of the comparison.
> Fix xcode analysis warnings

- libPhoneNumber/NSArray+NBAdditions.m
There is no reason to have an @synchronized here. An NSArray by itself is
immutable so it is thread safe. An NSMutableArray by definition is not thread
safe if it is being accessed/mutated on multiple threads.
Other small enhancements to reduce number of calls being made.
> Improve Array additions performance

- libPhoneNumber/NBNumberFormat.m
- libPhoneNumber/NBPhoneMetaData.m
- libPhoneNumber/NBPhoneNumberDesc.m
I believe that the coding and copy methods in these classes are unused.
I have disabled them behind an #ifdef flag.
If no one files any bugs, we can remove them.
> Remove unused methods

- libPhoneNumber.xcodeproj/project.pbxproj
- libPhoneNumber/NBMetadataHelper.m
- libPhoneNumber/NBPhoneNumberUtil.m
- libPhoneNumberTests/NBPhoneNumberParsingPerfTest.m
Improve phone number parsing performance ~28-32%
Improve phone number parsing performance by:
- Using NSCache to cache metadata, so when parsing phone numbers from different regions, the metadata cache is still going to be valid.
- Improve various methods in NBPhoneNumberUtil by removing redundant operations, or using a different construct that’s more performant (such as using NSCharacterSet instead of NSScanner to check if a string is a number).
Also added a performance test that reads sample phone numbers from the metadata, and parse them. Performance test can be enabled by defining PERF_TEST when compiling.
Performance improvement result:
Machine:
Mac Pro (Late 2013)
2.7 GHz. 12-Core Intel Xeon E5
64 GB 1866 MHz DDR3
macOS High Sierra 10.13.3
Phone number to parse count: 2688
Baseline …
> Improve phone number parsing performance by 28-32%

- libPhoneNumberTests/metadataGenerator
- libPhoneNumberTests/metadataGenerator.swift
New JSON metadata generator that can be run directly from command line (using `swift` command) without any dependencies — however, currently, this must be run on the Mac.
This generator pulls in metadata, metadata for testing, and short number metadata directly from the latest commit on canonical libPhoneNumber GitHub repo.
> New JSON metadata generator

- libPhoneNumber-iOS.podspec
The podspec doesn't include the NBRegExMatcher.{h/m} files so compilation fails when using this library as a pod.
> Fix podspec to include NBRegExMatcher

- libPhoneNumber-iOS.podspec
Master was failing trying to find the `Internal` source files.
> Fix regex references in podspec

- libPhoneNumber/NBAsYouTypeFormatter.m
The removed line is not reachable.
I run the Coverity static analyzer in our code which uses the libPhoneNumber and flagged the line as not reachable. I think it is right. All paths in the switch statement before this line end up in a "return" keyword.
A separate reported issue not covered by this Pull Request:
Actually, there was a second issue reported, I think it might be intentional, but I did not feel knowledgeable enough to modify the code. In the switch case 3, one code path ends up in a return, the other path sets self.isExpectingCountryCallingCode_  to YES, but there is not break or comment about why it is not used. I think the break was not added so it falls-trough and the code in the "default" case could be executed. Anyways, a comment around case 3 on why a break is not used …
> Fix for issue flagged by static analyzer

- README.md
- libPhoneNumber.xcodeproj/project.pbxproj
When trying to build with carthage, I was getting the error "CoreTelephony is not available when building for platform xxx" with these platforms set.
Also fixed those readme links.
Please let me know if you would like to handle this issue differently.
> Fixed supported platforms when building with carthage.

- Package@swift-5.0.swift
Support for Swift 5.x, while still support swift 4.2.  
The only change is the addition of a swift 5 or higher copy of package.swift and the swift tools version indication in it.  
The current `Package.swift` does not work with Swift 5 projects.
> Add Package@swift-5.0.swift

- libPhoneNumber-iOS/libPhoneNumberiOS.h
Closes #313 
See the issue for reproduction details. This just adds the new header to the "umbrella header" (libPhoneNumberiOS.h).
> Fix 'umbrella header for module does not include...' error

- libPhoneNumber.xcodeproj/project.pbxproj
- libPhoneNumberGeocoding/Metadata/NBGeocoderMetadataHelper.m
- libPhoneNumberGeocoding/NBPhoneNumberOfflineGeocoder.m
It looks like merging #326 made **libPhoneNumberGeocoding** and **libPhoneNumberShortNumber** uncompilable. This effectively means that Carthage distribution have become useless as it always compiles all shared schemes.
This PR updates header imports to make all schemes compile again. If you can think about better solution I will be more than happy to help to make the project fully functional again.
> Fix header import

- libPhoneNumber-iOS.podspec
- libPhoneNumber-iOS/Info.plist
- libPhoneNumber.xcodeproj/project.pbxproj
As preparation for a new release I have updated the podspec version + set a proper `${MARKETING_VERSION}` to reflect same version number. I'd recommend to merge sibling PR #340 before this one in order to have latest and greatest metadata from upstream repo included. Together with recent merge of PR #331 and previous #314 this sounds like a reasonable release package to me, doesn't it @paween? (cmp. issue #329)
> Bump version to 1.0.3

- Package.swift
- Package@swift-5.0.swift
This removes errors and warnings when building with Xcode 12.
> SPM: Update min SDK & fix linker misses

- README.md
Update README to use singleton (fixed my issue based on #324)
> Update README to use singleton

- Package.swift
- Package@swift-5.0.swift
- Package@swift-5.5.swift
I added the linker dependency in https://github.com/iziz/libPhoneNumber-iOS/pull/333
watchOS does not contain this framework, so things won't correctly link by specifying it directly.
Looking at the Apple docs, this framework is only available for iOS and macOS, so I have updated the setting.
macOS linking is required for a Catalyst app to compile, and is available as of macOS 10.10.
I have verified it against my app on Xcode 12.5 with iOS, watchOS, and macOS Catalyst.
Further, I cleaned up the v4.1 Package.swift file by removing invalid arguments.
> CoreTelephony package fixes for watchOS

- libPhoneNumber/NBPhoneNumberUtil.h
- libPhoneNumberShortNumber/NBShortNumberUtil.m
sharedInstance must be used. Fix issue with instantiation in ShortNumberUtil.
> Disallow default init for NBPhoneNumberUtil.

- libPhoneNumber/NBAsYouTypeFormatter.m
We had this crash when `lastRange.location` was `NSNotFound` for an edgecasey phone number / locale combination. This adds a length check.
> Check if rangeOfString found something
